#!/bin/sh

set -e -x

GO_VER=${GO_VER:-1.5}

#mkdir go

export GOPATH="$PWD/go"

git clone https://github.com/influxdata/influxdb.git "$PWD"/go/src/github.com/influxdata/influxdb
docker run  --rm -it -v "${GOPATH}":/go -e "GOPATH=/go" -w /go/src/github.com/influxdata/influxdb/ golang:$GO_VER sh -c 'go get -u -f -t ./...'

cd go/src/github.com/influxdata/influxdb/

sh ./build-docker.sh
